spring.application.name=hotel-management-system

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hotel_system}
spring.datasource.username=admin
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

hotel.booking.max-days=365