spring.application.name=hotel-management-system

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hotel_system}
spring.datasource.username=admin
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

hotel.booking.max-days=365

spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false
logging.level.org.hibernate.SQL=ERROR