package io.github.wojtekolo.hotelsystem.booking.exception;

public enum BookingErrorCode {
    ONLY_PLANNED_STAY_CAN_BE_CANCELLED,
    CONFLICTING_INTERNAL_DATES,
    CONFLICTING_EXTERNAL_DATES,
    BOOKING_CANCELLED_CANNOT_BE_EDITED,
    BOOKING_COMPLETED_CANNOT_BE_EDITED,
    NOSHOW_BOOKING_CANNOT_BE_EDITED
}
