package io.github.wojtekolo.hotelsystem.booking.exception;

public enum RoomStayErrorCode {
    ONLY_PLANNED_STAY_CAN_BE_CANCELLED,
    ONLY_PLANNED_STAY_CAN_HAVE_START_DATE_EDITED,
    ONLY_PLANNED_STAY_CAN_HAVE_ROOM_EDITED,
    ONLY_PLANNED_OR_ACTIVE_STAY_CAN_HAVE_END_DATE_EDITED,
    ONLY_PLANNED_STAY_CAN_HAVE_PRICE_EDITED,
    FOUND_STAY_WITHOUT_STATUS,
    ROOM_NOT_FOUND,
    CANNOT_SET_END_DATE_IN_THE_PAST,
    CANNOT_SET_START_DATE_IN_THE_PAST
}
